### ISSUE TITLE
Spec test doesn't work?

### ISSUE THREAD

**Issue by seanliu93** [learn-co-students/javascript-intro-to-looping-v-000#1]
Hi. The spec test doesn't work. There are a bunch of lets and consts that are not allowing the spec test to run properly. Please fix this. Currently have no way of solving this lab and passing the tests.

**Comment by deniznida** [comment]
hey @seanliu93, I think you need to update your node version. To do that run `npm install -g n` in your terminal and `n latest`. After restating your terminal `learn` should work.

**Comment by seanliu93** [comment]
that worked. Thanks!

**Comment by deniznida** [comment]
awesome! Thanks for pointing this out.
